export default {
    SHOW_LOADER: "SHOW_LOADER",
    CURRENTLOCATION: 'CURRENTLOCATION',
    ORDER_DETAILS: "ORDER_DETAILS",
    IS_LOGGED_IN: 'IS_LOGGED_IN',
    USER_DATA: "USER_DATA",
    BOOKING_DATA: "BOOKING_DATA",
    BOOKING_DATA_PICKER: "BOOKING_DATA_PICKER",
    ADDRESS_DATA: "ADDRESS_DATA",
    VEHICLE_DATA: "VEHICLE_DATA",
    BANCK_ACCOUNT: "BANCK_ACCOUNT"
}