export const AuthRouteStrings = {
    SPLASH_SCREEN: "SPLASH_SCREEN",
    LOGIN_SCREEN: "LOGIN_SCREEN",
    USER_SIGN_UP:"USER_SIGN_UP",
    FORGOT_PASSWORD:'FORGOT_PASSWORD',
    ON_BOARDING:"ON_BOARDING",
    WELCOME_SCREEN:"WELCOME_SCREEN",
    OTP_SCREEN:'OTP_SCREEN',
    PROFILE_INFORMATION:'PROFILE_INFORMATION',
    KYC_SCREEN:"KYC_SCREEN",
    APPROVAL_SCREEN:"APPROVAL_SCREEN"

}
export const MainRouteStrings = {
    BOTTOM_TAB_ROUTES:"BOTTOM_TAB_ROUTES",
    USER_HOME_SCREEN: "USER_HOME_SCREEN",
    USER_PROFILE_SCREEN:"USER_PROFILE_SCREEN",
    ACTIVITY_SCREEN:"ACTIVITY_SCREEN",
    FAVORITES_SCREEN:"FAVORITES_SCREEN",
    BECOME_PICKER:"BECOME_PICKER",
    VEHICLE_VERIFICATION:"VEHICLE_VERIFICATION",
    PICKER_ACCOUNT:"PICKER_ACCOUNT"
    
}