export const AuthRouteStrings = {
    SPLASH_SCREEN: "SPLASH_SCREEN",
    LOGIN_SCREEN: "LOGIN_SCREEN",
    USER_SIGN_UP:"USER_SIGN_UP",
    FORGOT_PASSWORD:'FORGOT_PASSWORD',
    ON_BOARDING:"ON_BOARDING",
    WELCOME_SCREEN:"WELCOME_SCREEN",
    OTP_SCREEN:'OTP_SCREEN',
    PROFILE_INFORMATION:'PROFILE_INFORMATION',
    KYC_SCREEN:"KYC_SCREEN",
    APPROVAL_SCREEN:"APPROVAL_SCREEN"

}
export const MainRouteStrings = {
    BOTTOM_TAB_ROUTES:"BOTTOM_TAB_ROUTES",
    USER_HOME_SCREEN: "USER_HOME_SCREEN",
    USER_PROFILE_SCREEN:"USER_PROFILE_SCREEN",
    ACTIVITY_SCREEN:"ACTIVITY_SCREEN",
    FAVORITES_SCREEN:"FAVORITES_SCREEN",
    BECOME_PICKER:"BECOME_PICKER",
    VEHICLE_VERIFICATION:"VEHICLE_VERIFICATION",
    PICKER_ACCOUNT:"PICKER_ACCOUNT",
    TRAINING_SCREEN:"TRAINING_SCREEN",
    PICKER_DETAILS:"PICKER_DETAILS",
    ACTIVITY_SUMMERY:"ACTIVITY_SUMMERY",
    DISPUTE_SCREEN:"DISPUTE_SCREEN",
    PICKER_REVIEW_WHEN_CANCELLED:"PICKER_REVIEW_WHEN_CANCELLED",
    SET_DESTINATION:"SET_DESTINATION",
    ADDRESS_SCREEN:"ADDRESS_SCREEN",
    PAYMENT_METHOD:"PAYMENT_METHOD",
    RATING_AND_REVIEW:"RATING_AND_REVIEW",
    USER_KYC_SCREEN:"USER_KYC_SCREEN",
    EDIT_PROFILE:'EDIT_PROFILE',
    FIND_DESTINATON:"FIND_DESTINATON",
    SELECT_ADDRRESS_FROM_MAP:'SELECT_ADDRRESS_FROM_MAP',
    ITEMS_DETAILS:"ITEMS_DETAILS",



    PICKER_HOME_SCREEN:"PICKER_HOME_SCREEN"
}